### ISSUE TITLE
请教一下，运行按钮调用主函数时，为什么需要用Thread再设置setDaemon？

### ISSUE THREAD

**Issue by xJogger** [hxz393/BaiduPanFilesTransfers#1]
如题，这样调用有什么好处么？

**Comment by hxz393** [comment]
不使用多线程,点击运行时界面会卡死..

**Comment by xJogger** [comment]
> 不使用多线程,点击运行时界面会卡死..

哦哦，所以这么做是因为按下按钮之后，在按钮绑定的函数返回之前，整个界面都是处于不能操作的状态？

那setDaemon=True是为什么呢，我查到的是为了让主线程结束时，子线程会被立刻结束。而在thread_it函数中，t.start()之后，thread_it函数直接就结束了，那这时子线程，也就是main()函数不也就被结束了么。

**Comment by hxz393** [comment]
按钮直接绑定函数情况下,点击运行按钮,界面会一直假死等待函数跑完才反应过来,再一股脑吧结果输出.

使用setDaemon是为了防止强制销毁窗口后,线程还在后台跑的情况.虽然这里使用单线程请求,不会出现这个问题.但加了有好处,去了也没坏处.

**Comment by hxz393** [comment]
setDaemon用途参考:
https://segmentfault.com/a/1190000019748106

**Comment by xJogger** [comment]
> 按钮直接绑定函数情况下,点击运行按钮,界面会一直假死等待函数跑完才反应过来,再一股脑吧结果输出.
> 
> 使用setDaemon是为了防止强制销毁窗口后,线程还在后台跑的情况.虽然这里使用单线程请求,不会出现这个问题.但加了有好处,去了也没坏处.

哦哦，我突然明白了，主线程不是在thread_it函数运行完之后就结束了，而是返回了tk的mainloop。
啊，我太菜了，谢谢大佬的耐心解答。
