### ISSUE TITLE
可以支持http吗？

### ISSUE THREAD

**Issue by JasonQAQ** [hxz393/BaiduPanFilesTransfers#10]
我试了一下好像http协议的链接都失败了，https的没问题，可以解决这个问题吗？

**Comment by hxz393** [comment]
可以,下版改下好了

**Comment by JasonQAQ** [comment]
> 可以,下版改下好了
> 实际上http和https没差....也不知道为什么你们获得的链接会是http的

我发现问题不在http，在短链接，很多http分享链接还是短链接，这个能解决嘛？

**Comment by hxz393** [comment]
链接带有/share/link?shareid=的格式是吗?

**Comment by JasonQAQ** [comment]
https://pan.baidu.com/s/1skNuPVR 这样的链接

**Comment by JasonQAQ** [comment]
> 链接带有/share/link?shareid=的格式是吗?

https://pan.baidu.com/s/1skNuPVR 这样的链接

**Comment by JasonQAQ** [comment]
> 链接带有/share/link?shareid=的格式是吗?

我找到解决方法了，http://pan.baidu.com/s/1skNuPVR这样的网址改成https://pan.baidu.com/s/1skNuPVR#list/path=%2F这样的就行，就直接http改成https，然后末尾加上#list/path=%2F

**Comment by hxz393** [comment]
按理说你上面的链接,直接把http改成https就可以了
