### ISSUE TITLE
支持暂停/恢复

### ISSUE THREAD

**Issue by hoare211** [hxz393/BaiduPanFilesTransfers#102]
大佬，非常感谢您的开源；能否加个暂停/恢复的功能，我在转储的过程中，网盘满了，正在进行的转储没法暂停，后面都失败了，不得不看着程序，失败地跑完整个列表；最后，清理网盘，把任务再重新跑一遍。要是能暂停/恢复就好了。

**Comment by hxz393** [comment]
刚出现网盘满的提示时，直接通过右上角点击关闭程序就行了。
