### ISSUE TITLE
F12 找不到main请求和xfcs cookie

### ISSUE THREAD

**Issue by psp0001060** [hxz393/BaiduPanFilesTransfers#103]
你好，按照教程找COOKIE,找不到main请求和xfcs cookie。 无痕模式下也没有找到。

**Comment by hxz393** [comment]
要在你的主页，按 `F5` 刷新页面。在其他什么地方随便怎么点都找不到 `main`。
你可以先按 `F12` 打开调试器，然后（已登录帐号）直接访问主页网址：https://pan.baidu.com/disk/main

**Comment by psp0001060** [comment]
好用啦~
