### ISSUE TITLE
请问这类转存码可以在程序里转存吗

### ISSUE THREAD

**Issue by shootingstar693** [hxz393/BaiduPanFilesTransfers#104]
比如这种转存码，直接填在程序里会报错，求助大佬
ff31b257f5c1cb72c5bb50b5472970ad#40310984#今古奇观_（明）抱瓮老人编；冯裳标校_12053347_zhelper-search.zip

**Comment by hxz393** [comment]
在去年十一月份开始停止支持，你可以下个旧版本试试：https://github.com/hxz393/BaiduPanFilesTransfers/tree/2.3.3

**Comment by hxz393** [comment]
你这链接还是超星图书馆的源，现国内还有什么地方传新书的吗

**Comment by shootingstar693** [comment]
> 你这链接还是超星图书馆的源，现国内还有什么地方传新书的吗

ylibrary上搜的，那里书很全，可惜大部分都是秒传链接

**Comment by shootingstar693** [comment]
> 你这链接还是超星图书馆的源，现国内还有什么地方传新书的吗

另外报个问题，在macOS上，打包运行之后报错_tkinter.TclError: wrong # args: should be "wm iconbitmap window ?bitmap?"查了应该是因为源代码第80行self.root.iconbitmap(default=icon_path)多写了default，删了之后就好了

**Comment by hxz393** [comment]
> ylibrary上搜的，那里书很全，可惜大部分都是秒传链接

试了一下 ylibrary，数据基本来源 zlibrary，而且两种下载方式 IPFS 和秒传都不能用了。还是想办法上 zlibrary 吧

**Comment by hxz393** [comment]
> 另外报个问题，在macOS上，打包运行之后报错_tkinter.TclError: wrong # args: should be "wm iconbitmap window ?bitmap?"查了应该是因为源代码第80行self.root.iconbitmap(default=icon_path)多写了default，删了之后就好了

感谢反馈，我没在 macOS 上打过包，可能是创建临时文件的方法不支持。删除第 80 行后，程序没有图标，不影响功能使用。
