### ISSUE TITLE
能否找你定制呢，哈哈有没有联系方式！！！

### ISSUE THREAD

**Issue by yesft** [hxz393/BaiduPanFilesTransfers#109]
哈哈 期待大神的联系！！！

**Comment by hxz393** [comment]
请给我发邮件：hxz393@gmail.com

**Comment by hxz393** [comment]
功能已更新到主分支 2.8.0 版本，直接到[发布页](https://github.com/hxz393/BaiduPanFilesTransfers/releases/tag/2.8.0)下载即可。
