### ISSUE TITLE
不支持这种链接吗

### ISSUE THREAD

**Issue by aaaol** [hxz393/BaiduPanFilesTransfers#11]
https://pan.baidu.com/share/init?surl=

**Comment by hxz393** [comment]
嗯不支持,这类链接是17年以前生成的,至今还存活的甚少,不做适配了.

**Comment by aaaol** [comment]
> 嗯不支持，类型链接是17年以前生成的，至今仍存活的甚少，不做适应了。

我有挺多这种链接的 还是希望适配一下

**Comment by hxz393** [comment]
那请帮忙提供几个链接(单文件,文件夹,多文件类型)我测试下

**Comment by aaaol** [comment]
> 那请帮忙提供几个链接(单文件,文件夹,多文件类型)我测试下
https://pan.baidu.com/share/init?surl=RqR9MIZlnIKb9aJ7rLsaxw qy6p
https://pan.baidu.com/share/init?surl=-H_J_2rXOUqB1azYBcQhZw l3ot
https://pan.baidu.com/share/init?surl=5EQsiQ9Rz1qhl9552J_hCg zvaw
https://pan.baidu.com/share/init?surl=7lhfCcthoB2GnxJBgRpd4w gfom
https://pan.baidu.com/share/init?surl=XSRDLcgrEH_NJ1vMxcGWGw 33hn
https://pan.baidu.com/share/init?surl=QgZNkvb0pZzIzCfw0RC0Ow xpgb
https://pan.baidu.com/share/init?surl=EAijvw97309guxbrciJV-Q 0ymi
https://pan.baidu.com/share/init?surl=8nL6zCdURQM0lMRvpnaA1Q yqfn
https://pan.baidu.com/share/init?surl=niNXNZo69UEviEyotB3OjA p6a8
https://pan.baidu.com/share/init?surl=4jLG1-vTVw6W_1237VWMKQ irfq
https://pan.baidu.com/share/init?surl=0Dq1AYtLeMUk8nAsEkMkdw j7em
https://pan.baidu.com/share/init?surl=Qgn1Lo8r0T4jn8xjoVSzzA ci5t
https://pan.baidu.com/share/init?surl=MYiD2L7JvYkGc2Eirssd3Q ydc3
https://pan.baidu.com/share/init?surl=Y3JF11A_wNmQZiPkmGIG1w ght4
https://pan.baidu.com/share/init?surl=cFBa49w72Cwaq0yBRiTt8g 2xdb
https://pan.baidu.com/share/init?surl=MxnDYtbwna8bEGS2kEiZyQ gj87

只有单文件

**Comment by hxz393** [comment]
好,待我更新了再回复

**Comment by YoungYang2014** [comment]
http://pan.baidu.com/s/1c28B90O 这类链接也不支持，在浏览器里面打开这类链接  会转换格式为https://pan.baidu.com/share/init?surl=c28B90O

**Comment by hxz393** [comment]
在记事本中,使用替换功能,把所有链接中的

https://pan.baidu.com/share/init?surl=

替换成

https://pan.baidu.com/s/1

之后便可以正常使用软件转存了
