### ISSUE TITLE
提示：转存失败，转存文件数超过限制。遇到这种情况能否优化成分批保存。

### ISSUE THREAD

**Issue by liubo6324** [hxz393/BaiduPanFilesTransfers#112]

**Comment by hxz393** [comment]
去用现成脚本：[百度云批量保存](https://greasyfork.org/zh-CN/scripts/453280-%E7%99%BE%E5%BA%A6%E4%BA%91%E6%89%B9%E9%87%8F%E4%BF%9D%E5%AD%98)
