### ISSUE TITLE
百度云海外版本的批量分享大大能做一个么？

### ISSUE THREAD

**Issue by FFFFFFpy** [hxz393/BaiduPanFilesTransfers#115]
https://www.terabox.com/chinese
emmm，某个资源站爬下来的资源大多数都转存在百度云海外版

**Comment by hxz393** [comment]
什么资源会放到这个网盘？我下了多年东西，从没见过这个网盘的分享链接。

**Comment by FFFFFFpy** [comment]
写真emmmm,然后我刚刚尝试看一下它的日志，emmm做了防护的，F12呼不出开发者，通过其他方法呼出来了，会马上跳转空白页

**Comment by hxz393** [comment]
发我网站看看，如果来了兴趣可以写一个

**Comment by FFFFFFpy** [comment]
![IUPL9T~MXN`2JM@Z~G4_ZXM](https://github.com/user-attachments/assets/0dd5857d-aa41-4692-9b2a-c6c79f251630)
https://galleryepic.xyz/zh

**Comment by hxz393** [comment]
诶，我看到一些二次元 Coser 色图，没什么写真啊（大失所望

打开网盘看看，界面果然和百度网盘一个妈生的。然后开发者工具一开，好家伙！七百多个脚本请求？？？撑不到几秒钟自动跳空白页了。

路子太嘢，在下无从下手只能 respect:O
