### ISSUE TITLE
如何把分享链接文件转到企业网盘中

### ISSUE THREAD

**Issue by dvlp-org** [hxz393/BaiduPanFilesTransfers#116]

**Comment by hxz393** [comment]
请详细说说问题。企业版链接可以支持转存，企业版帐号不能获取 Cookies？

**Comment by Sage520** [comment]
> 请详细说说问题。企业版链接可以支持转存，企业版帐号不能获取 Cookies？

企业版和个人版请求地址不一样，我尝试直接改 BASE_URL 为 https://pan.baidu.com/mid_enterprise_v2 是不可以的，看了下请求企业版比个人版多了参数 ，比如 gettemplatevariable 接口多个cid之类的三四个参数

**Comment by hxz393** [comment]
> 看了下请求企业版比个人版多了参数

感谢告知细节，我没企业认证用不了。话说既然是企业版，内部找个开发改一改不算难事
