### ISSUE TITLE
主窗口启动位置在屏幕的中间偏下位置

### ISSUE THREAD

**Issue by huangten** [hxz393/BaiduPanFilesTransfers#117]
程序启动时，主窗口整体位置在屏幕中间偏下，并未整体居中。

self.place_window_center() 调用早于 _create_widgets()，导致设置启动位置时并获取到的 window 的宽度和高度为 0。

并未影响功能使用，只是每次启动不太方便。

**Comment by hxz393** [comment]
这是我自己要的效果，不要窗口居中，不会溢出屏幕就行了。绘制完成再移动窗口，在 ttkbootstrap 中看起来会有点蠢，先移动刚好掩盖了愚蠢的绘制过程
