### ISSUE TITLE
大佬，转存的时候可以输出文件名嘛

### ISSUE THREAD

**Issue by Timchacode** [hxz393/BaiduPanFilesTransfers#119]
像批量分享那样，批量转存也可以输出文件名的话，就方便做一份资源清单表格。

**Comment by hxz393** [comment]
可以，但有一个问题：百度网盘旧版可以生成带多个文件的单条链接，我不知道这种链接返回的文件名信息是怎样。手头上没有这种链接来测试，你能帮我找找吗？

**Comment by hxz393** [comment]
已更新到 2.8.1 版本中

**Comment by Timchacode** [comment]
感谢大佬！
