### ISSUE TITLE
批量转存带有指定目录的链接时存在指定目录和转存文件对不上的情况

### ISSUE THREAD

**Issue by Wilson-White** [hxz393/BaiduPanFilesTransfers#120]
详细描述：批量指定目录转存时如果遇到链接重复但是目标目录不重复的情况有可能会导致目录错位
经检查是由于如下代码导致要存在不同目录的重复的链接被去除，进而导致存储目录错位的情况，建议作者修改
`self.link_list = list(dict.fromkeys(normalized_links))`
`self.link_list_org = list(dict.fromkeys(link for link in raw_links if link))`

**Comment by hxz393** [comment]
在新版本 2.8.2 中已更新。也加入了你要的存储路径回显
