### ISSUE TITLE
填入百度ID和网址后显示无bdstoken

### ISSUE THREAD

**Issue by RoaringWind** [hxz393/BaiduPanFilesTransfers#2]
没获取到bdstoken,请检查cookie和网络后重试.
填入形式：BAIDUID=........:SL=0:FG=1
位置：空或者根目录下一个英文名文件夹
粘贴多个无密码分享链接

**Comment by hxz393** [comment]
cookie获取方式请参考:https://meta.appinn.net/t/topic/16995/25

**Comment by RoaringWind** [comment]
成功了！谢谢。之前我只复制了BAIDUID，后来填了所有的cookies就OK了
