### ISSUE TITLE
1.81 使用转存多条报错转 存失败,错误代码(2)

### ISSUE THREAD

**Issue by folochina** [hxz393/BaiduPanFilesTransfers#21]
转存成功:https://pan.baidu.com/s/1WYIGvkQiwsSqPV0-Pj9Ynw 12qw 
转存失败,错误代码(2):https://pan.baidu.com/s/10lphWzWjdI0wTUHurdF1cQ 12qw 

![image](https://user-images.githubusercontent.com/11660951/116572936-f5b0c000-a93e-11eb-8b72-7500e03edf5d.png)

**Comment by hxz393** [comment]
问题无法复现,原因不明...
![image](https://user-images.githubusercontent.com/5063578/116600722-310db780-a95c-11eb-82c9-9b1bcca792a5.png)

**Comment by liuhq0826** [comment]
好吧，我当时就是为了转存github上这个库才改的程序，所以这个是没问题的。

**Comment by folochina** [comment]
刚换了一台电脑是ok的 不报错，那就后面遇到这个问题的换个电脑操作吧

**Comment by folochina** [comment]
python初学者
debug半天发现我这电脑在验证码提取的那个cookie里面包含BDCLND这个参数 
后面转存方法返回就是200 然后错误2错误mgs为空

然后我自己加了这一行在验证码提取的位置删除掉BDCLND 进行验证，就没有错误了
虽然请求后又会加入BDCLND到里面去

居然原因未知，我另一台电脑没有任何错误不用改 都是win10，猜测百度判断的安全之类的设定

![image](https://user-images.githubusercontent.com/11660951/116647804-06e4e580-a9ae-11eb-891a-f4e8a2076a79.png)

**Comment by dolt131943** [comment]
遇到同样问题。一次都只能下第一个，后面的都失效。看起来跟上面的原因有点类似（即一次请求后，部分数据被变动了）。
如果第一个都是能成功的，那么每次请求都（重置）使用界面输入的Cookie，是不是就可以了。

**Comment by liuhq0826** [comment]
其实每次打开chrome的无痕模式，重新登录下百度网盘，获取cookie就可以了。我还真没遇见过你们说的问题

**Comment by hxz393** [comment]
> python初学者
> debug半天发现我这电脑在验证码提取的那个cookie里面包含BDCLND这个参数
> 后面转存方法返回就是200 然后错误2错误mgs为空
> 
> 然后我自己加了这一行在验证码提取的位置删除掉BDCLND 进行验证，就没有错误了
> 虽然请求后又会加入BDCLND到里面去
> 
> 居然原因未知，我另一台电脑没有任何错误不用改 都是win10，猜测百度判断的安全之类的设定
> 
> ![image](https://user-images.githubusercontent.com/11660951/116647804-06e4e580-a9ae-11eb-891a-f4e8a2076a79.png)

谢谢反馈.我猜测是由于在多个设备登录同一账号后才出现的使用问题.
按楼上所言,使用无痕模式下获取的cookie应该没毛病.

**Comment by dolt131943** [comment]
> 其实每次打开chrome的无痕模式，重新登录下百度网盘，获取cookie就可以了。我还真没遇见过你们说的问题

感谢回复，也感谢做了这个工具。

这问题可能是多设备没有全部退，我想起来我的那个账号还登录了IOS，Ipad等多个设备，回去全部退出一下再试试。

不过，上述现象是重新打开后还是可以下第一条，所以估计如果能够重置一个Cookie可能是可以的，但也可能请求不都完整了，不符合HTTP的回写Cookie的规范。

**Comment by folochina** [comment]
无痕模式可以解决
