### ISSUE TITLE
[feature]希望可以支持手机分享的格式

### ISSUE THREAD

**Issue by homexuanlv** [hxz393/BaiduPanFilesTransfers#24]
手机分享出来的格式是这样的，而且链接和提取码可能不在同一行
链接：https://pan.baidu.com/s/   提取码：      复制这段内容后打开百度网盘手机App，操作更方便哦--来自百度网盘超级会员V1的分享

**Comment by hxz393** [comment]
因为原始链接格式多种多样,所以不做适配.
可以在记事本中查找替换删除掉开头的 _链接：_ 即可.

**Comment by homexuanlv** [comment]
> 因为原始链接格式多种多样,所以不做适配.
> 可以在记事本中查找替换删除掉开头的 _链接：_ 即可.

谢谢了，如果是将偶数行和奇数行合并成一行记事本可以操作吗

**Comment by hxz393** [comment]
奇数行链接,偶数行提取码?用python处理很简单,读取文本后把奇数行和偶数行按顺序分别提取成为两个组,合并后写入到新的文档.
用Notepad++包括插件功能都没发现可以实现的方法...

**Comment by homexuanlv** [comment]
> 奇数行链接,偶数行提取码?用python处理很简单,读取文本后把奇数行和偶数行按顺序分别提取成为两个组,合并后写入到新的文档.
> 用Notepad++包括插件功能都没发现可以实现的方法...

太感谢了，最后用C写了个读写的，然后我问了别人发现微软的WORD的替换有这个功能

**Comment by hxz393** [comment]
今天刚好在炫音爬了一堆链接,格式就是一行链接一行提取码,我又拿notepad++试了试.

先是使用搜索标记功能标记链接行,全部剪切,剩下的全是提取码行,然后用列模式移到行第一列先打一个空格再粘贴.预想中每行都会变成 _链接 提取码格式_ ,结果大跌眼镜,变成了所有 _链接行+第一个提取码+所有链接行+第二个提取码_ ....的格式,总文档行数变成了链接数²行.Notepad++中如果选取时候用的是列模式,粘贴时也是列模式才能达到想要效果,不知道vim中是不是这样?

我又想到用正则匹配,Notepad++对正则支持很好所以成功了.替换时选择正则表达式模式,查找框填入表达式: `^(.{47})\r\n` 替换框填入`\1 `,直接全部替换就OK啦.

这里记一下,希望对你也有用.
