### ISSUE TITLE
程序运行无反应

### ISSUE THREAD

**Issue by uu-xixi** [hxz393/BaiduPanFilesTransfers#28]
依次按照格式要求填写Cookie、UserAgent、提取连接等。点击运行程序时，程序没有任何反应。

**Comment by hxz393** [comment]
运行环境是什么?

**Comment by LuckyMango** [comment]
> 运行环境是什么？
win10_x64

**Comment by hxz393** [comment]
信息太少无法确定故障原因.一般来说程序卡住不动是网络有问题造成程序一直在尝试重新连接,最多等个十分钟看看是否报超时问题

**Comment by LuckyMango** [comment]
> 信息太少无法确定故障原因.一般来说程序卡住不动是网络有问题造成程序一直在尝试重新连接,最多等个十分钟看看是否报超时问题
> 您好，我使用公司电脑和家里电脑都产生相同问题，网络正常。点击运行程序，程序无反应，等了半个小时还是无反应。程序应该没有卡死

**Comment by hxz393** [comment]
可能是使用网络代理软件的原因
