### ISSUE TITLE
访问链接返回错误代码(105)

### ISSUE THREAD

**Issue by JXA-a** [hxz393/BaiduPanFilesTransfers#29]
访问链接返回错误代码(105)
这个怎么解决？？

**Comment by threnhainan** [comment]
> 访问链接返回错误代码(105)
> 这个怎么解决？？

一样，显示错误（105）

**Comment by hxz393** [comment]
错误代码105代表链接格式不正确,可以检查一下链接行是否带有隐藏字符.
