### ISSUE TITLE
百度群组文件如何自动转存呢？

### ISSUE THREAD

**Issue by bzlihe** [hxz393/BaiduPanFilesTransfers#33]
请问，百度群组文件如何自动转存呢？

**Comment by hxz393** [comment]
在网页端转存

**Comment by icaca** [comment]
群文件太多了 能否想想办法分目录转存

**Comment by hxz393** [comment]
> 群文件太多了 能否想想办法分目录转存

我没有群组文件转存的经验，不知道群文件到底是怎么个多法？

**Comment by icaca** [comment]
tb或者海鲜上，有人会卖一些资源或素材，都是几百个目录，每个目录下面又有目录和文件。
我昨天手动试了下，一二级目录直接转存都会失败，三级目录大概存到第100个的时候也失败了，点进去发现还有2个目录和200多个文件。当然也有可能是转存的次数过多了。

因为群共享的文件也会更新。如果能实现群共享的目录，与特定目录进行同步，只转存增量，或许会比较好。


![image](https://github.com/hxz393/BaiduPanFilesTransfers/assets/279229/2415cdcb-85dd-4c58-ad94-253ee1b1bcc7)

**Comment by hxz393** [comment]
现在工具转存是基于网盘链接，但是群组文件似乎并没有链接？

**Comment by icaca** [comment]
看不到链接的

**Comment by hxz393** [comment]
> 看不到链接的

那么你觉得应该在 UI 方面怎么实现逻辑？例如我首先需要获取什么，执行什么操作，得到什么结果。

**Comment by icaca** [comment]
比如说，显示已加入的所有群，如图的1和2，可以获取到群名称。

选择源目录：
如果简单点可以直接选择群的名称，然后转存所有目录和文件。如果做得复杂一点，可以显示一个树形结构，让用户选一下源目录。
如果觉得麻烦，也可以按照你的要求手动输入也行。

选择目标目录：
可以显示根目录下的一级目录，然后放在所选的目录下面。当然也可以手动输入或者直接放在/下。

**Comment by hxz393** [comment]
你看功能是不是这个样子：https://www.1566xueshe.com/1572/
我不确定是否能用，你可以试一下。

**Comment by hxz393** [comment]
破解版原帖：
https://www.52pojie.cn/thread-1882639-1-1.html

**Comment by icaca** [comment]
看样子应该是的 但是不太敢用 e语言写的基本报毒

**Comment by hxz393** [comment]
> 看样子应该是的 但是不太敢用 e语言写的基本报毒

是的，我也不敢用。大概知道应有些什么功能：群列表、用户文件列表、群组文件列表、转存、同步。
这得新建个项目，换 `QT` 来写，感觉写出来类似 `PikPak` 非官方客户端。

还有就是，群组功能一般用户用不上，但对倒卖资源的来说很需要，特别是同步更新功能。出于个人立场，我不愿意帮助倒卖狗，不管有意无意，不管有偿无偿。

**Comment by icaca** [comment]
做生意的一般都有会员 我就是轻度网盘用户 别人分享了 又不能不用

**Comment by hxz393** [comment]
按需转存下载吧，如果是素材类的文件，可以叫分享者打包，减少文件数量。

**Comment by icaca** [comment]
三级目录都存不下来，咸鱼上买的东西哪有售后呀，不跑路都不错了。。。算了 偶尔用用就手动弄弄算了
