### ISSUE TITLE
错误尝试次数过多,请稍后再试

### ISSUE THREAD

**Issue by lanceleungssk** [hxz393/BaiduPanFilesTransfers#36]
一直出现“错误尝试次数过多,请稍后再试”，大佬们知道怎么解决吗？
1-cookie用的是main?from=homeFlow的，应该没问题；
2-测试用的转存文件链接和提取码都是正常的，可以转存；
3-我开了超级VIP；
4-我尝试了chrome和firefox2个浏览器，还是不行。
![7I RHB{J0DQCFWCXO}`RCJ2](https://user-images.githubusercontent.com/85343312/158504959-c93b28fd-e419-4757-8192-7e1416c5d579.png)

![WU@)2})GDN9NV{RDXSU A@K](https://user-images.githubusercontent.com/85343312/158504971-4b2261be-5e43-4a57-aca0-a8ed1490c938.png)

**Comment by Doublefire-Chen** [comment]
+1，我也遇到了相同的问题

**Comment by hxz393** [comment]
如果链接列表中有验证码错误的网盘链接,反复试错三五次后就会出现这个错误,账号访问只能等待十分钟后解封.
检查一下是否是这个原因呢?

**Comment by Doublefire-Chen** [comment]
> 原先版本中如果链接列表中有验证码错误的网盘链接,反复试错三五次后就会出现这个错误,账号访问只能等待十分钟后解封. 新版我晚上再测试一下,目前转存秒传链接是没有问题.

但是我的链接列表的提取码没有错，我手动试过的

**Comment by Doublefire-Chen** [comment]
> 原先版本中如果链接列表中有验证码错误的网盘链接,反复试错三五次后就会出现这个错误,账号访问只能等待十分钟后解封. 新版我晚上再测试一下,目前转存秒传链接是没有问题.

不过百度有一点毛病，明明是正确的提取码，还显示错误，并弹出个验证码，输入验证码后才显示提取码正确。把浏览器所有的缓存啥的都删除一遍，可以解决这个验证码的问题，但不能解决软件的问题

**Comment by hxz393** [comment]
已经查到是错误提示,错误返回码对不上的问题,我需要大量链接测试一下各种情况.

**Comment by hxz393** [comment]
已经修复问题.

**Comment by hxz393** [comment]
> 提取码，还显示



> 不过百度有一点毛病，明明是正确的提取码，还显示错误，并弹出个验证码，输入验证码后才显示提取码正确。把浏览器所有的缓存啥的都删除一遍，可以解决这个验证码的问题，但不能解决软件的问题

带提取码的网盘链接连续发送三次提取码(不管对错)就会弹验证码,必须手动访问链接解决掉验证码,方能再次访问这个链接.软件这边提示是'尝试次数过多'.
