### ISSUE TITLE
提示缺少api-ms-win-core-path-l1-1-0.dll 

### ISSUE THREAD

**Issue by mmfan** [hxz393/BaiduPanFilesTransfers#37]
提示缺少api-ms-win-core-path-l1-1-0.dll。但是我已经安装[Visual C++ 微软常用运行库合集_2022.04.09]了！还提示

**Comment by hxz393** [comment]
安装vc_redist运行库试试:
 https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe
https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe

**Comment by mmfan** [comment]
> 安装vc_redist运行库试试: https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe

提示已安装！！我卸载重装试试

**Comment by mmfan** [comment]
> 安装vc_redist运行库试试: https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe
下载重装重启还是提示缺少！！

**Comment by mmfan** [comment]
> > 安装vc_redist运行库试试: https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x64.exe https://download.microsoft.com/download/9/3/F/93FCF1E7-E6A4-478B-96E7-D4B285925B00/vc_redist.x86.exe
> > 下载重装重启还是提示缺少！！

知道了！win10 64一下系统不支持吧！！

**Comment by hxz393** [comment]
可以自行到win7下编译成exe文件,python3.5以上版本都支持的

**Comment by wuyinwuxian** [comment]
我同样遇到了这个问题，提示缺少api-ms-win-core-path-l1-1-0.dll，是否要求电脑必须安装python（我使用的是发布的最新版本exe文件）

**Comment by houjie1979** [comment]
我也是win7遇到同样问题，自行打包即可：
1. 安装支持win7的最高版本 https://www.python.org/downloads/release/python-388/ 
2. git clone代码到本地
3.  pip install pyinstaller chardet six
4. 执行打包，在工程根目录执行 pyinstaller -F -w -i bpftUI.ico bpftUI.py  会在dist目录生成bpftUI.exe
5. 运行bpftUI.exe，如果能启动就应该可以用了，用法参照作者说明。

**Comment by hxz393** [comment]
新版向下降级到3.6，又可以使用了
