### ISSUE TITLE
转存失败,转存文件数超过限制:https://pan.baidu.com/s/XXXXxxxxx 5ZSG  

### ISSUE THREAD

**Issue by jupitors** [hxz393/BaiduPanFilesTransfers#38]
最新版本 无法保存提示超过限制，

**Comment by hxz393** [comment]
升级vip或手动保存,这个限制软件破不了.

**Comment by hxz393** [comment]
> 大佬是否可以加一下，超过限制就递归新建文件夹转存，直至转存成功呢

有专做这功能的工具,我就不重复造轮子了.

**Comment by zyk-miao** [comment]
我是svip 依然遇到了 转存失败,转存文件数超过限制 
有专做这功能的工具,我就不重复造轮子了.
能否分享下这个工具

**Comment by hxz393** [comment]
https://github.com/acheiii/BaiduFilesTransfers_Pro
