### ISSUE TITLE
能否把bpftUI.py分成UI 和 util两个部分

### ISSUE THREAD

**Issue by Jack-XHP** [hxz393/BaiduPanFilesTransfers#39]
我利用bpftUI中的helper function 和bypy 实现了通过RSS自动转存并自动下载的

https://github.com/Jack-XHP/BaiduPanFilesTransfers

在使用过程中需要把bpftUI中的TK mainloop comment了才能正常import 其中的helper function。 能不能修改一下UI的代码让TK gui在import时不会运行？

**Comment by hxz393** [comment]
已更新到dev分支
