### ISSUE TITLE
转存提示：访问链接返回错误代码

### ISSUE THREAD

**Issue by ZHT131** [hxz393/BaiduPanFilesTransfers#43]
用1.10.2版本转存提示：访问链接返回错误代码

**Comment by CookieSir** [comment]
我也是提示 转存失败,错误代码(-6)

**Comment by hxz393** [comment]
可以使用.-6状态码没有对应记录,可能是cookie导致的问题.

**Comment by CookieSir** [comment]
> 可以使用.-6状态码没有对应记录,可能是cookie导致的问题.

但是点转存后，保存目录不存在已经自动新建出来了

**Comment by CookieSir** [comment]
> 可以使用.-6状态码没有对应记录,可能是cookie导致的问题.

我换到谷歌浏览器无痕模式下获取的cookie  确实可以正常使用了  谢谢
