### ISSUE TITLE
转存失败,目录中已有同名文件或文件夹存在

### ISSUE THREAD

**Issue by li8523892** [hxz393/BaiduPanFilesTransfers#44]
希望出一个同名文件或文件夹加后缀的办法来解决这个问题。

**Comment by hxz393** [comment]
可以转存到另外一个新建的空目录来规避此问题

**Comment by CookieSir** [comment]
目前软件还能用？ 我怎么转存都报错：转存失败,错误代码(-6)

**Comment by kiss5523** [comment]
> 么转存都报错：转存失败,错误代码(-6)

我也是显示这个错误了

**Comment by hxz393** [comment]
> > 么转存都报错：转存失败,错误代码(-6)
> 
> 我也是显示这个错误了

错误代码-6是cookie不全

**Comment by zp976** [comment]
> > > 么转存都报错：转存失败,错误代码(-6)
> > 
> > 
> > 我也是显示这个错误了
> 
> 错误代码-6是cookie不全

我一开始也以为是cookie不全 ，后来查到是
-6的含义的登录失败，请重新登录
重新登录后就好了

**Comment by kiss5523** [comment]
> 
后来我解决了、然后文件的数据还是需要开通vip
