### ISSUE TITLE
此应用无法在你的电脑上运行

### ISSUE THREAD

**Issue by CafeBabe202** [hxz393/BaiduPanFilesTransfers#49]
无法打开软件，系统提示：此应用无法在你的电脑上运行
win10 21H2

**Comment by hxz393** [comment]
同21H2版本,没有出现过这个问题.
系统是否32位?打包的程序是64位.其他可能造成这报错原因我也想不到.

**Comment by CafeBabe202** [comment]
我好像是32位的虚拟机，希望可以有直接的python代码，对于linux用户，exe反而不方便，谢谢

**Comment by hxz393** [comment]
克隆项目后可以在本地运行.
