### ISSUE TITLE
支持长链接，不支持短链接

### ISSUE THREAD

**Issue by caibai36** [hxz393/BaiduPanFilesTransfers#50]
可能暂时还有提供长链接的转存功能。
长链接都能成功，短链接暂时不能转存。

输入：第一行是长链接的例子，第二行是短链接的例子
-------------------------------
https://pan.baidu.com/s/1jue6m3X7yd3yNbUC9l3rtQ 提取码: 2qd7
http://pan.baidu.com/s/1sjlYA9R 提取码: y57u

输出：长链接的都能成功，短链接暂时不能转存。
-------------------------------
转存成功
不支持链接:http://pan.baidu.com/s/1sjlYA9R 提取码: y57u

**Comment by hxz393** [comment]
原因是第二个链接使用的http而不是https.
http不被支持,改成https即可.

**Comment by hxz393** [comment]
已经在dev分支增加处理http://链接,可自行更新.

**Comment by caibai36** [comment]
真的诶，太厉害了。确实从http变到https就可以转存了。非常感谢这么快回复，这个软件很有用。
