### ISSUE TITLE
转存失败，错误代码：2

### ISSUE THREAD

**Issue by haifenggo** [hxz393/BaiduPanFilesTransfers#52]
转存失败，错误代码：2 是怎么回事啊？

**Comment by hxz393** [comment]
未记录或变更的返回代码.
在网页端访问或转存是否正常?如果访问不了,提示是什么?

**Comment by haifenggo** [comment]
网页端可以手动保存，
使用那个软件就提示转存失败，错误代码：（2）

**Comment by haifenggo** [comment]
翻看了closed issues ，使用chrome无痕模式的cookie，已经转存成功了！虽然不知道什么原理。。

**Comment by haifenggo** [comment]
使用chrome无痕模式的cookie只能批量转存一次，第二次还是错误代码（2），
百度网盘会创建 “保存目录+时间” 的文件夹，但是不会转存。

**Comment by hxz393** [comment]
可能是转存时有同名文件回报代码改了,我今天测试下看

**Comment by haifenggo** [comment]
> 可能是转存时有同名文件回报代码改了,我今天测试下看

经过昨晚的疯狂验证，已经搞清楚这bug了。
就是保存文件路径不能输入多层目录，
如   \计算机书籍\C++ ，这样虽然会创建文件，但是会提示转存失败，错误代码，
输入  C++   就能转存成功
本来想修改源码，为开源做出自己的贡献，... 。

**Comment by hxz393** [comment]
转存前会先尝试创建文件夹,这一步带\是能成功新建子目录.
但是转存时目标目录带\会失败(转存秒传格式链接会成功)报-2返回码,以至于后续转存出现一些莫名其妙的报错,非要重新登录刷新Cookie才能正常工作.
这个修改会影响转存秒传格式链接功能,所以不修改,使用时注意下就好.
