### ISSUE TITLE
可以添加一个定时转存功能

### ISSUE THREAD

**Issue by Laelwz** [hxz393/BaiduPanFilesTransfers#55]
一次性大量链接转存会导致
“链接错误尝试次数过多,请手动转存或稍后再试”
能否添加冷却时间如一秒一次转存这种来规避。

**Comment by Laelwz** [comment]
![image](https://user-images.githubusercontent.com/96306603/187360377-7e8288b3-ac94-436d-b5a0-f1a2b2b49b2c.png)
还有一次一条链接转存的话，会出现一些空目录，但是转存是成功的，希望解决。

**Comment by hxz393** [comment]
第一个问题.
这个大量的限额约1000个,之后需要冷却多久并不知道.如有测试结果望告知.

第二个问题.
填写了转存目录后,在转存之前会先检测目录是否存在.存在则直接使用,不存在则新建目录.
只有新建目录后转存失败才会出现空目录,转存成功文件即会在目录下面.
转存成功但文件不在目标目录内按理是不可能.可述之你的操作步骤.

**Comment by Laelwz** [comment]
第一个问题：
这个冷却已经两天了仍然存在，我每天都会试一试。
每次填写一条链接转存暂时可以曲线救国，所以希望能有冷却机制来规避。

第二个问题：
可能是我描述不清，不好意思。
我填写了cookie和ua，然后放一条链接，点击转存，以此往复，每次都只放一条链接点击转存。
然后转存成功了，文件也在目标目录内了，但是每次转存都会增加一个如上个回复中图里所示的空目录。

**Comment by hxz393** [comment]
两个问题都是一个原因.实际表现是打开每个连接都要求输入验证码,程序也提示稍后再试,而等了两天依然不会自动恢复.

解决方法是在浏览器上登出当前账户,打开Chrome无痕模式(重要)窗口登录,获取新的Cookie填入程序.

**Comment by hxz393** [comment]
最新测试,1000转存后出现"数据错误,请稍后重试"提示为IP层限制.
可以通过更换代理服务器来破除限制.
