### ISSUE TITLE
可不可以添加一个功能，每个链接对应不同的文件路径名称

### ISSUE THREAD

**Issue by pkr5277** [hxz393/BaiduPanFilesTransfers#56]
可不可以添加一个功能，每个链接对应不同的文件路径名称

**Comment by hxz393** [comment]
一般只有不同链接中文件有不同解压密码时,需要分用不同文件夹保存.我是一条一条执行转存.
其他时候好像没这么做的必要,只需下载后在本地电脑整理.

如果这一需求很频繁,可以自行修改源码.源码"执行转存文件"下面对变量"dir_name"进行重新赋值,可以来自于单独文本文件,也可以直接写在程序中.
或者干脆点也可以指定"链接","提取码"和"保存目录"这3个变量来源于特定格式文本文件,而不依赖软件GUI文本框获取值,满足定制化需求.
