### ISSUE TITLE
Go格式链接可能会没有-crc32参数

### ISSUE THREAD

**Issue by 627992512** [hxz393/BaiduPanFilesTransfers#57]
例如：
BaiduPCS-Go rapidupload -length=1073741824 -md5=f6ff598f5c6cd1b67acbe374fcf42ede -slicemd5=3784269cc3be7993fb9b827ef96ebead "Windows_10_x64-disk1.z04"
BaiduPCS-Go rapidupload -length=1073741824 -md5=91ea94011c183cc38f60f4279f92363a -slicemd5=af672ccc27fde8c324875de543f0c23f "Windows_10_x64-disk1.z01"
这种也是可以转存

**Comment by 627992512** [comment]
goname感觉可以直接用：
go_name = re.findall(r'"(.*)"', url_code)[0].replace('"', '').replace('/', '\\').strip()
这样匹配

**Comment by hxz393** [comment]
感谢提供的信息
