### ISSUE TITLE
能否增加为每个链接设置转存时生成对应的目录

### ISSUE THREAD

**Issue by zdoek001** [hxz393/BaiduPanFilesTransfers#59]
因为有些链接的资源命名是乱七八糟的。如果可以在转存前为每个链接设置对应的转存目录名，那就可以在转存时更好的整理。

**Comment by hxz393** [comment]
可以自行改程序实现.
百度网盘正确使用方法是把资源下载到本地再整理,不要花心思去整理网盘中文件结构.
