### ISSUE TITLE
建议开发定期拉取上游分享的更新

### ISSUE THREAD

**Issue by gobiking** [hxz393/BaiduPanFilesTransfers#6]
有些分享链接动不动10G+，上游更新了那些内容也不知道，只能全量下载，替换本地文件，很费时间

**Comment by hxz393** [comment]
懂你的意思,但更新的部分怎么处理?我想有三种方式:
1.建议分享方,把更新内容单独放以日期命名的文件夹;
2.使用第三方下载工具,在文件已存在情况下会自动跳过;
3.保存分享链接内容到目录后,使用百度云自带去重功能.保留上次保存的文件夹中文件,去除本次保存的文件夹中重复文件.之后本次保存的目录内只有更新内容了.

**Comment by gobiking** [comment]
需要服务器，我赞助个华为云上海区的4cpu，8g内存，2m带宽的机器给你做后端

**Comment by hxz393** [comment]
更新的部分存放单独文件夹还是合并到已存在文件夹内?
后一种情况好处理,不需要记录任何信息.
前一种情况就需要记录上次保存文件夹和文件信息,对比取出差异文件列表再转存,是不是这个意思?

**Comment by hxz393** [comment]
主要问题是,使用百度提供接口需要单独申请token,没有普适性,我觉得不适合集成到这一工具中.
单独写个脚本封装到docker容器,再放到服务器去跑比较好.

**Comment by hxz393** [comment]
使用OAuth方式转存可以到这边参考:
https://github.com/iyzyi/BaiduYunTransfer
