### ISSUE TITLE
网盘批量转存只有第一个成功其余全部失败

### ISSUE THREAD

**Issue by ykl007** [hxz393/BaiduPanFilesTransfers#61]
你好大大，请问网盘批量转存只有第一个成功其余全部失败，这是什么情况？能修复吗？
![image](https://user-images.githubusercontent.com/110618606/203016056-34be56e3-6659-48ab-949d-93e40a3f3dfc.png)

**Comment by hxz393** [comment]
Cookies的问题.可以在Chrome浏览器使用隐私模式打开百度网盘获取新Cookies来解决.最好是完全关闭Chrome浏览器后再开隐私模式.

**Comment by ykl007** [comment]
好的谢谢大大的回答，再请教一个问题，就是我们转存链接有最高限制吗？比如说最高转存100,200这样的限制

**Comment by hxz393** [comment]
连续转存超过1000个左右会报错,即使在网页端也无法手动转存,要等一个小时才好.

**Comment by ykl007** [comment]
好的了解了，很感谢您的解答
