### ISSUE TITLE
还是提示连接尝试次数过多，建议增加转存间隔

### ISSUE THREAD

**Issue by lingyue103** [hxz393/BaiduPanFilesTransfers#64]
看来是秒转接口又挂了，已经提示 ”链接错误尝试次数过多,请手动转存或稍后再试“，是否可以尝试在转存时增加时间间隔。。。宁愿多等一会吧

**Comment by hxz393** [comment]
我测试使用1.13版本目前正常.如果秒传转存失败,会等待1秒钟后重试.
