### ISSUE TITLE
没有服务器版本吗

### ISSUE THREAD

**Issue by 839781960** [hxz393/BaiduPanFilesTransfers#65]

**Comment by hxz393** [comment]
命令行版本?

**Comment by 839781960** [comment]
> 命令行版本?

对，就是下载，然后转存到阿里哈哈，另外这个代码失效了。

**Comment by 839781960** [comment]
这个转存大量就直接弹失败，没有递归子文本然后折半二分转存

**Comment by hxz393** [comment]
这个只有转存没有下载,刚刚试过转存OK.百度云下载命令行版本在Github上有不少个实现,可以搜一搜.
目前转存使用的Cookies隔两天就会失效,需要在Chrome无痕模式下重新登录百度网盘获取.
一次最多转存传统分享连接的数量是1000,超过1000会封锁转存.只能等待(约1个小时)解封,没有其他办法.
秒传连接转存没有限制,也没有Cookies失效问题.

**Comment by hxz393** [comment]
更新了 2.0 版本，可以自行导入相关函数到自己程序中。
