### ISSUE TITLE
批量转存的时候，中间需要加sleep时间，不然会触发频繁操作，导致出现验证码，然后报错

### ISSUE THREAD

**Issue by glenq** [hxz393/BaiduPanFilesTransfers#66]
![image](https://user-images.githubusercontent.com/17242230/232246229-4e3abf73-d700-4ae5-9372-2524cfafb9d5.png)

贴3个进去，第一个链接会成功，后面两个就会失败。手工一个一个的贴就没问题

**Comment by hxz393** [comment]
不要反复尝试错误的提取码...错误尝试过多,所有链接都弹验证码.
这个情况可以在浏览器无痕模式重新获取cookie,并尝试没有转存过的链接.
