### ISSUE TITLE
请问有针对群文件的转存工具吗，现在好像只能转存公共链接的文件

### ISSUE THREAD

**Issue by nature21** [hxz393/BaiduPanFilesTransfers#67]

**Comment by hxz393** [comment]
没有,有什么好的分享文件群可以发我试试.

**Comment by jiuyaoxing** [comment]
我也正在找批量转存百度群组的工具，组好可以读取群组文件，右键某个文件夹，批量转存，网上搜了工具可以（密道转存V12），不过是收费软件。

**Comment by hxz393** [comment]
我没用过群组文件转存，请问一下什么场景下会用到群组文件？

**Comment by jiuyaoxing** [comment]
> 我没有用过群组文件转存，请问一下下面会用到实例文件吗？

现在很多资料分享会在“百度网盘群组”里面，群文件分享文件资料，群里人员自己查看群文件，自己想保存那个文件，选中，左上角有个转存到自己网盘。一般这种都是收费群，全员禁言，资料很多，所以一点点存很费事。

**Comment by hxz393** [comment]
收费群模式目前来看很小众，可能还需要配套“转存群组文件夹中新增文件”功能。如果收费的群组转存工具好用，花点钱也无妨。

**Comment by jiuyaoxing** [comment]
> 收费群模式目前看来，可能还需要安装“转存群组文件夹中新增文件”功能。如果收费的群组转存工具好用，花点钱也无妨。

恩，我加入的是一个百度云盘财会群，初级、中级、注会、实操、考研、考公资料都有，都是最新的，群主还是免费分享的。资料太多，就是转存麻烦些。

**Comment by Joackk** [comment]
如果是好友分享的批量文件，能批量转存吗？

**Comment by hxz393** [comment]
> 如果是好友分享的批量文件，能批量转存吗？

格式是怎样的？

**Comment by hxz393** [comment]
> 就一个文件夹，里面是分类文件夹，在里面就是文件，这种

没有链接是吧？叫好友生成个分享链接就能转存了。

**Comment by ffaffAHA** [comment]
> 我也正在找批量转存百度群组的工具，组好可以读取群组文件，右键某个文件夹，批量转存，网上搜了工具可以（密道转存V12），不过是收费软件。

我也在找这种工具，大哥，你找到了吗？

**Comment by hxz393** [comment]
#33
