### ISSUE TITLE
 只能转存不超过500？

### ISSUE THREAD

**Issue by kent2019eason** [hxz393/BaiduPanFilesTransfers#7]
超过500，会提示参数错误，无法突破500数量，数量转存对比官方网页转存有啥优势嘛

**Comment by hxz393** [comment]
适合批量转存不适合超量转存.不过我可以改一改,发个测试链接给我看看?

**Comment by kent2019eason** [comment]
链接：https://pan.baidu.com/s/1ohMjmuGAZOIJ2JmMh0H4Ig 
提取码：1314 
复制这段内容后打开百度网盘手机App，操作更方便哦
共1500个文件，120个文件夹，速度慢一点可以理解，希望能分批，但可以不手动分批，而保存这些文件

**Comment by kent2019eason** [comment]
> 适合批量转存不适合超量转存.不过我可以改一改,发个测试链接给我看看?

链接：https://pan.baidu.com/s/1-2bH5dj3fZg21mMQmomQsA 
提取码：1314 
复制这段内容后打开百度网盘手机App，操作更方便哦
共1500个文件，120个文件夹，速度慢一点可以理解，希望能分批，但可以不手动分批，而保存这些文件

**Comment by kent2019eason** [comment]
> 适合批量转存不适合超量转存.不过我可以改一改,发个测试链接给我看看?

链接：https://pan.baidu.com/s/1Z52C6iMopOfdB0AefwqIYg 
提取码：y0g4 
复制这段内容后打开百度网盘手机App，操作更方便哦
共1500个文件，120个文件夹，速度慢一点可以理解，希望能分批，但可以不手动分批，而保存这些文件

**Comment by kent2019eason** [comment]
> 适合批量转存不适合超量转存.不过我可以改一改,发个测试链接给我看看?

链接发出去，就失效....  你再试试     链接：https://删除pan.baidu.com/删除s/1mFvaDRsA删除EnEBNJ-PyZCEig 
提取码：zoe2 
共1500个文件，120个文件夹，速度慢一点可以理解，希望能分批，但可以不手动分批，而保存这些文件

**Comment by kent2019eason** [comment]
你留给邮箱，我邮箱发给你吧

**Comment by hxz393** [comment]
用户名@gmail.com

**Comment by hxz393** [comment]
不是发送就失效...是分享的文件中有被禁止内容,生成即失效,你可以把分享文件数控制一下,多个文件夹,超过500个文件就行

**Comment by hxz393** [comment]
刚才写好试了一下效果,下面详细讲讲.
1.当得到错误代号'120'时(有两个错误代号,前面代号和目录内已存在同名文件夹共用'12')表示有转存限制,VIP是200000,非vip500.响应返回中只会提示,要转存的文件数有多少,超过了500限制转存失败.
这个提示信息错误今后版本中会修正区分.

2.假设链接中有3个文件夹,第一个里面文件有600,第二个文件数400,第三个文件夹里面又分立文件夹,分别装有400和600个文件.
当得到转存限制提示时,我将依次访问四个文件夹获取文件列表(客户端有统计文件夹中文件数的功能,但网页端没有这个接口).
访问超多文件目录时,网页一次只返回100个文件列表,用url中的page参数来控制分段获取.

3.因此我将5次获取文件列表动作视为一个回合,不超过5次访问,也就是文件数不超过500个的文件夹,直接执行转存文件夹.
超过5次的,先建立对应同名目录,再进行500个文件转存.之后接着获取文件列表,直到文件列表获取完毕所有文件都转存为止.

4.理想状态下程序访问百度网盘的频率是每秒钟一个来回,这么算起来:
转存第一个文件夹花时为:6次获取文件列表的时间+1次建立文件夹的时间+2次文件转存的时间=9秒钟
转存第二个文件夹花时为:4次获取文件列表的时间+1次文件夹转存的时间=5秒钟
转存第三个文件夹花时为:1次访问文件夹的时间+10次获取文件列表的时间+1次文件夹转存的时间+1次建立文件夹的时间+2次文件转存的时间=15秒钟
再加其他发送提取码,获取随机码的时间总共耗时35秒钟.
这是理想状态下,非理想状态可能整个流程要60秒钟到90秒钟,而我的retrying重试等待时间最多是不会超过30秒钟,这一流程和等待时间实在太长了.
如果文件夹和文件数再多一些,想象下点击保存按钮之后,程序就卡在那半天不动,你不知道他是程序死机了呢,网络卡住了呢,还是正在转存工作中,这么算来又要加一个信息框来专门展示这类转存信息.

5.就目前粗浅跑起来,代码量已经增加快一倍了.而效果我觉得没法接受.
好久以前我也有过转存限制的烦恼,那时候记得VIP是5000,现在看已经几乎无限了.而且也没碰到过一个链接放那么多文件的情况.
所以这个功能我不加了,实在是得不偿失(代码越多,问题越多).我看到别人有写类似的东西,或者你可以去试试.

**Comment by kent2019eason** [comment]
&nbsp; 1.非常感谢如此详细的介绍。批量保存500文件以下的文件夹，您的软件是比较完善了。
&nbsp; 2.因为目前百度网盘超级会员是和朋友合租，想把自己的文件备份保存到自己网盘中，累计了太多，就想着能快速保存。
&nbsp; 3.而目前来看，开一次超级会员，先全量备份一次，以后用您的软件增量转存，这样是最合适的方案了。
&nbsp; 4.刚学python没多久，从您的代码中获益良多。再次感谢。



---原始邮件---
发件人: "assassing"<notifications@github.com&gt;
发送时间: 2020年10月17日(周六) 下午5:25
收件人: "hxz393/BaiduPanFilesTransfers"<BaiduPanFilesTransfers@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"kent2019eason"<3469914899@qq.com&gt;;
主题: Re: [hxz393/BaiduPanFilesTransfers]  只能转存不超过500？ (#7)




 
刚才写好试了一下效果,下面详细讲讲.
 1.当得到错误代号'120'时(有两个错误代号,前面代号和目录内已存在同名文件夹共用'12')表示有转存限制,VIP是200000,非vip500.响应返回中只会提示,要转存的文件数有多少,超过了500限制转存失败.
 这个提示信息错误今后版本中会修正区分.
 
2.假设链接中有3个文件夹,第一个里面文件有600,第二个文件数400,第三个文件夹里面又分立文件夹,分别装有400和600个文件.
 当得到转存限制提示时,我将依次访问四个文件夹获取文件列表(客户端有统计文件夹中文件数的功能,但网页端没有这个接口).
 访问超多文件目录时,网页一次只返回100个文件列表,用url中的page参数来控制分段获取.
 
3.因此我将5次获取文件列表动作视为一个回合,不超过5次访问,也就是文件数不超过500个的文件夹,直接执行转存文件夹.
 超过5次的,先建立对应同名目录,再进行500个文件转存.之后接着获取文件列表,直到文件列表获取完毕所有文件都转存为止.
 
4.理想状态下程序访问百度网盘的频率是每秒钟一个来回,这么算起来:
 转存第一个文件夹花时为:6次获取文件列表的时间+1次建立文件夹的时间+2次文件转存的时间=9秒钟
 转存第二个文件夹花时为:4次获取文件列表的时间+1次文件夹转存的时间=5秒钟
 转存第三个文件夹花时为:1次访问文件夹的时间+10次获取文件列表的时间+1次文件夹转存的时间+1次建立文件夹的时间+2次文件转存的时间=15秒钟
 再加其他发送提取码,获取随机码的时间总共耗时35秒钟.
 这是理想状态下,非理想状态可能整个流程要60秒钟到90秒钟,而我的retrying重试等待时间最多是不会超过30秒钟,这一流程和等待时间实在太长了.
 如果文件夹和文件数再多一些,想象下点击保存按钮之后,程序就卡在那半天不动,你不知道他是程序死机了呢,网络卡住了呢,还是正在转存工作中,这么算来又要加一个信息框来专门展示这类转存信息.
 
5.就目前粗浅跑起来,代码量已经增加快一倍了.而效果我觉得没法接受.
 好久以前我也有过转存限制的烦恼,那时候记得VIP是5000,现在看已经几乎无限了.而且也没碰到过一个链接放那么多文件的情况.
 所以这个功能我不加了,实在是得不偿失(代码越多,问题越多).我看到别人有写类似的东西,或者你可以去试试.

**Comment by Milloyy** [comment]
插一句，我现在还没有试用这个项目的功能，似乎不支持转存大批量文件？我觉得支持批量转存才是项目的灵魂所在，转存500个以下的文件可以直接在网页端完成，不需要多此一举。但实际操作中，比如考研资料、编程资料随随便便就超过了500个文件（尽管不是每个文件都有用，但转存期间也不好剔除），使用批量转存工具无非是想把重复工作交给计算机，省去新建文件夹这类繁琐工作。再者就如作者所举例的转存2000个文件非理想状态大概需要90秒，就这个时间也还可以接受，总比手工复制文件夹名称逐个新建好。所以作者不妨考虑考虑实现在个功能，转存过程应该不需要与程序交互，命令行实现，一步操作一句提示输出也挺好。

**Comment by hxz393** [comment]
1.使用频次高我还是建议开百度VIP账户,没有转存限制.
2.网络上有突破500限制转存软件,通过网页模拟点击方式实现,就是速度慢.最理想的方法是用百度网盘API来实现,可需要申请用户token.等我有空会去看一看.

感谢建议!
