### ISSUE TITLE
运行出错 'utf-8' codec can't decode byte 0xa1 in position 172: invalid start byte

### ISSUE THREAD

**Issue by Amagi5206** [hxz393/BaiduPanFilesTransfers#71]
你好，我在转存时提示

运行出错，请重新运行本程序。错误信息如下：
'utf-8' codec can't decode byte 0xa1 in position 172: invalid start byte

请问是什么原因呢？

**Comment by Amagi5206** [comment]
又试了几条秒传链，有些可以，有些不行

**Comment by Amagi5206** [comment]
附上其中一条会出现这个问题的秒传

https://pan.baidu.com/#bdlink=RUM0NjJFQzQ3QjI4RkJFRjE4NzRDQ0Q2Q0M3RUE5MTQjRjhEMDU5OTJBODFDNjFCRjc5OUYxOEQzNTgxNzVFNDUjMjUwOTEyMjM4I6G+UkowMTA2MDQ3NqG/ob5NUDOhv6G+MjAyMy0wNS0yN6G/LmV4ZV9IVw==

直接用浏览器的秒传插件是可以成功保存的，但是用批量转存工具不行

**Comment by hxz393** [comment]
可能是链接解码时有问题，我调试一下

**Comment by hxz393** [comment]
已修复并更新版本，看下还有没问题

**Comment by fengjiyang** [comment]
你好，我也在转存时提示utf-8的相关问题，以下是错误描述

运行出错，请重新运行本程序。错误信息如下：
'latin-1' codec can't encode characters in position 56-68: Body ('ウチはもう、延期できない。') is not valid Latin-1. Use body.encode('utf-8') if you want to send it encoded in UTF-8.

**Comment by fengjiyang** [comment]
这是出错秒传：12955f681596ed2743810ec3eafaa6d3#2363751131#ウチはもう、延期できない。.PC

**Comment by hxz393** [comment]
> 这是出错秒传：12955f681596ed2743810ec3eafaa6d3#2363751131#ウチはもう、延期できない。.PC

使用版本 1.1.1 可以转存

**Comment by Amagi5206** [comment]
> 已修复并更新版本，看下还有没问题

谢谢谢谢！已经解决了。

抱歉顺便再问一下提示 转存失败，文件名有非法字符 这种有办法解决嘛？

**Comment by hxz393** [comment]
> > 已修复并更新版本，看下还有没问题
> 
> 谢谢谢谢！已经解决了。
> 
> 抱歉顺便再问一下提示 转存失败，文件名有非法字符 这种有办法解决嘛？

发下链接给我调试，也许报错码代表的意思变了

**Comment by Amagi5206** [comment]
> > > 已修复并更新版本，看下还有没问题
> > 
> > 
> > 谢谢谢谢！已经解决了。
> > 抱歉顺便再问一下提示 转存失败，文件名有非法字符 这种有办法解决嘛？
> 
> 发下链接给我调试，也许报错码代表的意思变了

https://pan.baidu.com/#bdlink=MzYzOUJENDVCRDIwODFCRjhEQTAxQjlDMTYyNzNEREUjQUIxRTkwQjg1MkE1NTE5NTY3ODdFNjFFMzQ3M0IzN0EjMjkxNDkxMjY3NSNSSjAxMDYyNTU2LmV4ZV9LSQ0KNUQyNzNGNTAxREM3MDI2QzBCMkFBRENFRkExNkM5RTQjRjhEMDU5OTJBODFDNjFCRjc5OUYxOEQzNTgxNzVFNDUjMzc1NTAwMDcwI6G+UkowMTA2MjU1NqG/ob5NUDOhv6G+MjAyMy0wNS0zMKG/LmV4ZV9RUw==

这是其中一条 谢谢

**Comment by hxz393** [comment]
解码后其实是两条（多条）链接，这种第一次碰到。等我更新

**Comment by hxz393** [comment]
> > > 这是出错秒传：12955f681596ed2743810ec3eafaa6d3#2363751131#ウチはもう、延期できない。.PC
> > 
> > 
> > 使用版本 2.1.1 可以转存
> 
> 我使用的版本就是 2.1.1
因为我这边转存你的链接没有问题，所以只能你来测试。
这样，你先试下 2.1 版本转存看是否能成功。我不确定是否刚才改的代码有问题。
如果还是一样的问题，然后试下修改链接中的目标文件名 `ウチはもう、延期できない。.PC` 为英文看能否转存成功。
最后还不成功，试着换一台电脑执行转存试试。然后提供更多转存失败的链接给我。

**Comment by hxz393** [comment]
> https://pan.baidu.com/#bdlink=MzYzOUJENDVCRDIwODFCRjhEQTAxQjlDMTYyNzNEREUjQUIxRTkwQjg1MkE1NTE5NTY3ODdFNjFFMzQ3M0IzN0EjMjkxNDkxMjY3NSNSSjAxMDYyNTU2LmV4ZV9LSQ0KNUQyNzNGNTAxREM3MDI2QzBCMkFBRENFRkExNkM5RTQjRjhEMDU5OTJBODFDNjFCRjc5OUYxOEQzNTgxNzVFNDUjMzc1NTAwMDcwI6G+UkowMTA2MjU1NqG/ob5NUDOhv6G+MjAyMy0wNS0zMKG/LmV4ZV9RUw==
> 
> 这是其中一条 谢谢

更新 2.2.0 版本可以支持这类链接了

**Comment by fengjiyang** [comment]
> > > > 这是出错秒传：12955f681596ed2743810ec3eafaa6d3#2363751131#ウチはもう、延期できない。.PC
> > > 
> > > 
> > > 使用版本 2.1.1 可以转存
> > 
> > 
> > 我使用的版本就是 2.1.1
> 
> 因为我这边转存你的链接没有问题，所以只能你来测试。 这样，你先试下 2.1 版本转存看是否能成功。我不确定是否刚才改的代码有问题。 如果还是一样的问题，然后试下修改链接中的目标文件名 `ウチはもう、延期できない。.PC` 为英文看能否转存成功。 最后还不成功，试着换一台电脑执行转存试试。然后提供更多转存失败的链接给我。

解决了，是我的svip账号的问题，我重新注册了个新号就可以用，但是这样似乎也无法解决我svip账号用不了秒传的问题.....

**Comment by hxz393** [comment]
> 解决了，是我的svip账号的问题，我重新注册了个新号就可以用，但是这样似乎也无法解决我svip账号用不了秒传的问题.....

> 现在旧的百度账号已经无法使用秒传，只有新注册才可以


我想知道你的测试结果。因为从报错来看似乎并不和账号有关系，怀疑是我的代码问题。

假设是账号问题，那么到底是哪个环节出了问题呢？我需要更多错误报告。

**Comment by hxz393** [comment]
> 从我使用的工具和从网友交流中来看，是账号的问题；原先我一直使用的是mengzonefire的秒传油猴插件，但是最近几天突然一直转存失败，然后传出mengzonefire停止维护插件的消息。我用你的插件出现了上述报错。从网友的交流中，有一部分的svip账号是无法使用秒传的，所以我注册了一个信号，结果是mengzonefire和你的插件都可以转存成功。结论：账号的问题

我看到有人说是会员和非会员的问题，但是用另一个非会员的账号转存成功。
另外看到说是 smd5('slice-md5': rapid_data[1]) 缺失造成。或许我可以试试别的转存接口，但没法测试有没有效。
