### ISSUE TITLE
运行出错，请重新运行本程序。错误信息如下: list index out of range

### ISSUE THREAD

**Issue by Amagi5206** [hxz393/BaiduPanFilesTransfers#73]
感觉这应该是个新的bug所以新开了一贴 OvO

运行出错，请重新运行本程序。错误信息如下：
list index out of range

此为链接，同样试过用浏览器插件可以保存，用工具无法保存。

https://pan.baidu.com/#bdlink=YzA0YjhiYzBmZDBkMWRhMjMzODUwZGM0NmIyOGY3YjAjMTQwODcyMDY2I1JKNDMxMzk1LnppcF9LQw==

**Comment by hxz393** [comment]
是个新写的bug，已经修复了：）
