### ISSUE TITLE
百度网盘 cookie 输入不正确，请检查 cookie 后重试。

### ISSUE THREAD

**Issue by sep6738** [hxz393/BaiduPanFilesTransfers#74]
我输入了正确的cookie，但还是出现了这个报错

**Comment by hxz393** [comment]
它说错了就是错了，请用 Chrome 浏览器获取 Cookie 。

如果你使用 Chrome 浏览器获取的 Cookie 还是报错，请继续反馈。

**Comment by sep6738** [comment]
感谢大佬，Chrome&nbsp;的没问题，不过还是发现了其他问题







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月31日(星期三) 晚上8:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hxz393/BaiduPanFilesTransfers] 百度网盘 cookie 输入不正确，请检查 cookie 后重试。 (Issue #74)





 
它说错了就是错了，请用 Chrome 浏览器获取 Cookie 。
 
如果你使用 Chrome 浏览器获取的 Cookie 还是报错，请继续反馈。

**Comment by hxz393** [comment]
有问题可以随意发出来，我改代码很快

**Comment by Lemon-cc-hang** [comment]
我用 chrome 复制的 cookie 还是 报错 “百度网盘 cookie 输入不正确，请检查 cookie 后重试。”， 没有带双引号，直接复制的完整的cookie，难道还需要什么操作吗

**Comment by hxz393** [comment]
> 我用 chrome 复制的 cookie 还是 报错 “百度网盘 cookie 输入不正确，请检查 cookie 后重试。”， 没有带双引号，直接复制的完整的cookie，难道还需要什么操作吗

不需要别的操作，如果 Cookie 中带有特殊字符，或者没有找到 BAIDUID= 字段就会报这个。你可以检查一下你输入的 Cookie。

**Comment by Killyice** [comment]
我刚瞅了瞅浏览器里的Cookie，发现BAIDUID更新成了BAIDUID_BFESS，于是cookie检查出错，手动改成BAIDUID就正常了……

**Comment by hxz393** [comment]
> 我刚瞅了瞅浏览器里的Cookie，发现BAIDUID更新成了BAIDUID_BFESS，于是cookie检查出错，手动改成BAIDUID就正常了……

感谢告知，不过我这边测试结果中，有BAIDUID=也有BAIDUID_BFESS=，这两内容是一样的。
把代码中的`self.cookie.find('BAIDUID=')`改成`self.cookie.find('BAIDUID')`就可以了。
