### ISSUE TITLE
短链接的秒传转存失败

### ISSUE THREAD

**Issue by xepo123** [hxz393/BaiduPanFilesTransfers#76]
短链接的接口被封了。 
bd6bf38e771eb23f1f9023def6e366e0#dff4a80fb4902e17ac9f5747c0a8bd1c#724650932#DCyett.7zf

**Comment by hxz393** [comment]
是的，现在只能等个解决方案。

**Comment by lzsq520** [comment]
目前有新的秒传方案，格式：MD5＃MD5s＃大小＃文件名的 妙传链接可以使用 ，[脚本链接](https://greasyfork.org/zh-CN/scripts/427628-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E7%A7%92%E4%BC%A0%E9%93%BE%E6%8E%A5%E6%8F%90%E5%8F%96-%E6%9C%80%E6%96%B0%E5%8F%AF%E7%BB%B4%E6%8A%A4%E7%89%88%E6%9C%AC)
