### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by a97115038** [hxz393/BaiduPanFilesTransfers#78]
不用设置限制提交1000个链接
程序转存1000个链接后，可以休息一段时间在继续转存
设置每次转存的时间间隔，转存速度太快也是会限制的

**Comment by hxz393** [comment]
有没有测试过这个“休息一段时间”是多长时间？之前我测试一直不能恢复，所以把等待时间交给各位测试。

**Comment by a97115038** [comment]
就在上个月，用按键精灵，自己录制了脚本，把所有链接txt，逐行一条一条读取，然后抓图，保存，链接格式https://pan.baidu.com/s/1jI18NaA?pwd=63p3打开网页，读取图标，自动保存关闭浏览器，在打开一条链接，，速度慢，但是稳定，4w条数据，1H1G腾讯云垃圾服务器，转存了一星期

**Comment by a97115038** [comment]
我也是没有办法，很多脚本都不稳定，还要考虑用户什么等级，普通用户还是VIP，就由他们自己设置就好了

**Comment by a97115038** [comment]
一台服务器转存。另外一台服务器按照删除占位文件，怕爆盘

**Comment by hxz393** [comment]
下个星期我有大量链接需要转存，可以顺便测试一下：
1.短时间内转存 1000 条，帐号被限制转存（换 IP 无用，不是跳验证码，而是转存直接报错），需要等待多久或者用什么方式能恢复继续转存。
2.在上面一条测试无果的情况下，测试每次转存后等待多久能安全持续运行。如果能通过的话，可以把 1000 条限制去除，同时加入自定义等待时间。

对了，1000 条转存限制只针对普通百度分享链接，秒传链接没有限制，一个小时能转存 1 万多条。所以我也可能测不出来。

**Comment by a97115038** [comment]
任何脚本所受到的限制，就是不符合手动操作规律，百度网盘没有批量转存不同用户分享链接的功能，只有批量转存群文件（群文件的链接貌似和其它分享链接不一样）在加上网盘有等级限制，还有各个用户网络链接不一致，许多因素，比如我们正常转存一个链接复制黏贴在转存，所需要的时间。就是符合的，

**Comment by a97115038** [comment]
以前用油猴下载百度资源，最后限速3K-6KB的速度，后来我就马上开会员，还是3-6K的速度，过了好几天才恢复正常会员速度
