### ISSUE TITLE
关于"超过限制就递归新建文件夹转存，直至转存成功"工具问题

### ISSUE THREAD

**Issue by tasty007** [hxz393/BaiduPanFilesTransfers#79]
"大佬是否可以加一下，超过限制就递归新建文件夹转存，直至转存成功呢
-->有专做这功能的工具,我就不重复造轮子了"

大佬能否分享个这个工具的地址...

**Comment by hxz393** [comment]
试了一下之前提到的破除转存限制工具：有一个已不能用，有一个收费，那还不如冲百度网盘会员。
所以不想冲百度网盘会员，还是在网盘页面手动转存吧。如果需求很频繁，可以用按键精灵录制转存动作重复使用。
