### ISSUE TITLE
错误提示：链接失效，没获取到 user_id

### ISSUE THREAD

**Issue by shishiwow** [hxz393/BaiduPanFilesTransfers#82]
链接失效，没获取到 user_id，请问是我使用有问题还是？

**Comment by hxz393** [comment]
请尝试用不同浏览器获取 cookie

**Comment by nyano** [comment]
同上。多个浏览器获取cookie仍全部失败。
另外，firefox获取的cookie好像不识别？

**Comment by hxz393** [comment]
先退出所有浏览器中的帐号登录，用 Chrome 浏览器的无痕模式登录，获取 cookie。如有问题继续反馈。
 
有些版本 Firefox 浏览器存在的智障行为，用 F12 打开开发者模式获取 cookie 时，如果 cookie 太长，会截断并用省略号显示。可以观察一下。

**Comment by hxz393** [comment]
#83
