### ISSUE TITLE
使用直链没问题，使用任何秒传错误提示：链接失效，没获取到 user_id：

### ISSUE THREAD

**Issue by andy55444** [hxz393/BaiduPanFilesTransfers#83]

**Comment by hxz393** [comment]
换号可以转存吗？

**Comment by andy55444** [comment]
还没尝试，不过之前尝试了秒传脚本本来可以转存的现在全军覆没了，大概率不能通过换号就可以解决了。

**Comment by hxz393** [comment]
因为我还可以正常转存秒传链接，所以不清楚到底哪里的问题。可以肯定的是，在多次转存失败后得到返回错误码为2，这个错误码之前被自定义为没获取到 user_id 的返回，现在代表的错误原因不明。

**Comment by hxz393** [comment]
2.3.0 版本更新后，暂时修复短链接的秒传转存功能。
