### ISSUE TITLE
只有第一条转存成功，过了很久再试还是只能成功一条

### ISSUE THREAD

**Issue by qicaiyun** [hxz393/BaiduPanFilesTransfers#85]
提示请手动转存什么的，难道别人都能正常使用么？

**Comment by qicaiyun** [comment]
用的是链接+提取码

**Comment by hxz393** [comment]
从两方面解决：
一方面将链接放到记事本中，保证去除看不见的字符串后，再粘贴进软件转存；
另一方面用chrome浏览器无痕模式登录百度网盘获取cookie，再尝试转存。
试试能不能解决你的问题。
