### ISSUE TITLE
转存失败，秒传文件名冲突：949B4F916921EF3D08064D4E56097CAA#B2A6E5B7DBCAFFE2C1831CE2204A91B9#14528910819#果w.rar 

### ISSUE THREAD

**Issue by AlexZhengLiu** [hxz393/BaiduPanFilesTransfers#86]
cookies，access_token都换过了，也换了文件保存位置，每次都显示秒传文件名冲突。求教

**Comment by hxz393** [comment]
这个链接没有问题，我这边保存成功，足足有 13GB 大。看一下你的网盘剩余空间是否足够。
转存其他文件是否也不行？

**Comment by AlexZhengLiu** [comment]
> 这个链接没有问题，我这边保存成功，足足有 13GB 大。看一下你的网盘剩余空间是否足够。 转存其他文件是否也不行？

其他可以，就这个刚好不行，网盘还有很多空间，是因为之前用其他秒传插件的原因吗

**Comment by hxz393** [comment]
和网页插件不冲突，可以配合使用。

在百度官方文档中没提到错误代码 31039：
https://pan.baidu.com/union/doc/okumlx17r
知乎上说是上传文件时会报的错：
https://www.zhihu.com/question/567186526

所以我现在也没什么能做的。

**Comment by mengzonefire** [comment]
31039是因为目前使用的这个接口有百度的傻逼风控机制，使用海外ip访问就会触发

解决方法：
https://xtsat.github.io/rapid-upload-userscript-doc/document/FAQ/%E9%94%99%E8%AF%AF%E4%BB%A3%E7%A0%81(%E7%BD%91%E9%A1%B5%E5%B7%A5%E5%85%B7).html#服务器错误-31039

**Comment by hxz393** [comment]
> 31039是因为目前使用的这个接口有百度的傻逼风控机制，使用海外ip访问就会触发

感谢提供信息，如果不改转存文件名，是否多尝试转存几次也能成功？

**Comment by mengzonefire** [comment]
> 感谢提供信息，如果不改转存文件名，是否多尝试转存几次也能成功？

没测试过，应该是不行，31039这个已知是直接检测文件名

转存不稳定的那个是返回的errno：2，具体原因位未知，多次重试可解

这套接口逻辑与原秒传脚本接口一致，基本可套用逻辑

**Comment by hxz393** [comment]
> 没测试过，应该是不行，31039这个已知是直接检测文件名

行，先用改文件名的方式处理试试。
