### ISSUE TITLE
解决短链秒传接口的随机errno: 2问题

### ISSUE THREAD

**Issue by mengzonefire** [hxz393/BaiduPanFilesTransfers#89]
测试发现只要在请求header内加上"Content-Type": "application/x-www-form-urlencoded"即可修复短链接口不稳定的问题，可提高效率以及免去漫长的15次retry
方法来自：[脚本3.1.8版本更新](https://greasyfork.org/zh-CN/scripts/468633-%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98%E7%A7%92%E4%BC%A0%E8%BD%AC%E5%AD%98%E5%8A%A9%E6%89%8B-%E6%94%AF%E6%8C%81pc%E5%8F%8A%E7%A7%BB%E5%8A%A8%E7%AB%AF-%E6%B0%B8%E4%B9%85%E6%97%A0%E5%B9%BF%E5%91%8A%E7%BB%BF%E8%89%B2%E7%89%88)

**Comment by hxz393** [comment]
测试可行。
之前一百个转存会有一个最终报 “errno: 2”，加上请求头参数后，初步测试一次报错也没有。
感谢热心提供信息，已更新小版本。
