### ISSUE TITLE
批量保存问题添加时间间隔

### ISSUE THREAD

**Issue by a186232641** [hxz393/BaiduPanFilesTransfers#90]
可以加个时间间隔，太快的话就会提示：链接错误尝试次数过多，请手动转存或稍后再试

**Comment by hxz393** [comment]
看主页说明，通常是提取码错误，跳验证码了。你可以验证一下，直接访问链接看是不是这个原因？
正常转存只有一千条限制，没有转存速度限制。毕竟是用单线程运行，速度本来就很慢了。

**Comment by 805333** [comment]
能否写一个根据规则来删除重复文件的工具

**Comment by hxz393** [comment]
> 能否写一个根据规则来删除重复文件的工具

你可以提个思路，我参考一下。但肯定不是这个工具应该做的。
