### ISSUE TITLE
您好，比如我有两级目录我怎么表示呢

### ISSUE THREAD

**Issue by SarahSmitho** [hxz393/BaiduPanFilesTransfers#91]
![image](https://github.com/hxz393/BaiduPanFilesTransfers/assets/56591685/83f39cf4-52dc-469a-af3f-a65a30a79a81)
比如说  学习资料 android代码 我怎么办

**Comment by hxz393** [comment]
用 `/` 来表示。你的例子中为：`学习资料/android代码`
