### ISSUE TITLE
批量转存文件或目录名冲突，申请添加转存序号目录

### ISSUE THREAD

**Issue by haolovedan** [hxz393/BaiduPanFilesTransfers#96]
您好：
感谢您的这个工具，很好用；
比如批量转存100个链接，会有很多文件或文件名冲突导致转存失败，目录结构会很乱
能否添加一个功能，比如转存100个链接，然后转存过来的目录结构为 test/1 ~ test/100 ，转存过来的文件放在序号下面，请百忙之中抽空看一下能否添加一下这个功能，万分感激！

**Comment by hxz393** [comment]
可以添加，但只能以数字作为子目录名字。

例如转存目录填入test，第一个链接存在test/1中，第二十个链接存在test/20中。
预计添加一个勾选框，勾选后达成上诉转存结果。

由于每次转存前要额外建立文件夹，所以代码结构要重新整理一下。

**Comment by haolovedan** [comment]
非常感谢！
非常可以解决我遇到的问题。

**Comment by haolovedan** [comment]
麻烦您帮考虑一下编号可能出现的乱序问题，比如100个链接 里面如果有失效的或者链接错误的，也请创建个空目录进去，规避对不上号的问题，非常感谢。

**Comment by hxz393** [comment]
> 麻烦您帮考虑一下编号可能出现的乱序问题，比如100个链接 里面如果有失效的或者链接错误的，也请创建个空目录进去，规避对不上号的问题，非常感谢。

可是可以，不过按正常逻辑，失效链接是不建立文件夹的。例如第十九个链接失效，那么会缺少test/19。这样看一眼test目录能知道缺了哪些，而不用再进入目录内去确认。

**Comment by haolovedan** [comment]
嗯嗯，可以，最后不乱序就行，比如19链接失效了，然后第20个链接存到了test/19，不会出现这个情况就行，非常感谢！

**Comment by hxz393** [comment]
功能已新增，下载最新 `2.4.0` 版本，勾选「安全转存」再转存试试。

**Comment by haolovedan** [comment]
非常感谢，我去试试
