### ISSUE TITLE
 带提取码的链接无法提取

### ISSUE THREAD

**Issue by SoulDee** [hxz393/BaiduPanFilesTransfers#99]
电脑：win 10  专业版 + win7 专业版 一共三台电脑
账号：两个不同的账号
IP：两个不同的 IP
Cookie：正常模式和无痕模式都测试了

直接分享的没有提取码的都可以正常，但是带提取码的就是提示缺少提取码，格式反复检查是正确的

格式测试过以下格式：
- [链接 提取码]
- [链接?pwd=提取码]
- [链接 提取:提取码]

![image](https://github.com/hxz393/BaiduPanFilesTransfers/assets/33686436/f903e874-3a40-4400-a2df-56c526685616)

**Comment by hxz393** [comment]
链接本身测试过没有？只有页面标题为「百度网盘 请输入提取码」时才会出这个提示。有一种情况是输入提取码页面出验证码了，需要手动处理一下。

**Comment by SoulDee** [comment]
我今天又测试了一下，如果把同一个链接格式改成 [链接?pwd=提取码] 这种在网页可以直接跳转到转存页面的就可以提取，但如果是 [链接 提取码] 这种格式就不行。
